language: node_js
dist: xenial # 操作系统是 ubuntu xenial
node_js:
  - 12.16.2

cache:
  - npm
  - yarn

before_install:
  - npm install -g yarn
  - yarn install

script:
  # - yarn lint
  - yarn test
  - yarn build

notifications:
  email:
    recipients:
      - 2411mail@gmail.com
      - shooter.hero@gmail.com
      - syuukawa@hotmail.com
    on_success: never # default: change
    on_failure: always # default: always

before_deploy:
  - mv dist synapse-extension
  - rm synapse-extension.zip synapse-extension.asc # 保持clean的env
  - zip -q -r synapse-extension.zip synapse-extension # 打包压缩
  - shasum -a 256 synapse-extension.zip | tee synapse-extension.asc # 校验值并输出结果到console

deploy:
  provider: releases # 操作 releases 页面
  token: $GITHUB_TOKEN
  file:
    - synapse-extension.zip
    - synapse-extension.asc
  skip_cleanup: true
  on: #  只有打 tag 时才运行 deploy 阶段
    tags: true
